apiVersion: v1
kind: Service
metadata:
  name: adguard-http-https
  namespace: adguard
  labels:
    app: adguard-server
spec:
  selector:
    app: adguard-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      port: 8443
      targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard
spec:
  type: LoadBalancer
  ports:
    - name: udp
      port: 53
      protocol: UDP
    - name: tcp
      port: 53
      protocol: TCP
  selector:
    app: adguard-server