secretGenerator:
  - name: adguard-secrets
    namespace: adguard
    literals:
      - adguard_ip=${{ secrets.adguard_ip }}
resources:
  - 050-Service.yaml
patchesJson6902:
  - target:
      kind: Service
      name: "adguard-lb"
      version: v1
    path: patch.yaml
---
resources:
  - 010-Namespace.yaml
  - 020-Issuer.yaml
  - 021-Cert.yaml
  - 030-Volumes.yaml
  - 040-Deployment.yaml
  - 060-Ingress.yaml