namespace: adguard

resources:
  - 010-Namespace.yaml
  - 020-Issuer.yaml
  - 021-Cert.yaml
  - 030-Volumes.yaml
  - 040-Deployment.yaml
  - 050-Service.yaml
  - 060-Ingress.yaml

secretGenerator:
  - name: adguard-secrets
    literals:
      - adguard_ip=${{ secrets.adguard_ip }}

patchesJson6902:
  - target:
      kind: Service
      name: adguard-lb
      version: v1
    patch: |-
      - op: replace
        path: /spec/loadBalancerIP
        valueFrom:
          secretKeyRef:
            name: adguard-secrets
            key: adguard_ip
  - target:
      kind: Service
      name: adguard-lb-dns
      version: v1
    patch: |-
      - op: replace
        path: /spec/loadBalancerIP
        valueFrom:
          secretKeyRef:
            name: adguard-secrets
            key: adguard_ip