kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-volume-claim
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi