apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  namespace: helloworld
  annotations:
    external-dns.beta.kubernetes.io/hostname: hello.nekomade.com
    external-dns.beta.kubernetes.io/ttl: "120"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes