kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: dev
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/local-volumes/dev"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi