apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev
spec:
  type: LoadBalancer
  loadBalancerIP: 158.69.157.243
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql