apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev
  labels:
    app: postgres
spec:
  type: LoadBalancer
  loadBalancerIP: 158.69.157.240
  externalIPs:
    - 158.69.157.240
  ports:
    - port: 5432
  selector:
    app: postgres