# Database - MYSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: hieu-wordpress
  labels:
    app: wordpress
    tier: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: db_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: wp-data
              subPath: database
              mountPath: /var/www/html
      volumes:
      - name: wp-data
        persistentVolumeClaim:
          claimName: wp-volume-claim
# Web app - Wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: hieu-wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: library/wordpress:5.6.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_NAME
              value: wordpressDB
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: db_password
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-passs
                  key: db_username
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wp-data
              subPath: wordpress
              mountPath: /var/www/html
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: wp-volume-claim