apiVersion: v1
kind: Service
metadata:
  name: ps-server-lb
  namespace: ps-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 22001
    - name: https
      port: 443
      targetPort: 22001
    - name: app
      port: 22001
      targetPort: 22001
  selector:
    app: ps-server
  externalIPs:
    - 158.69.157.242