apiVersion: v1
kind: PersistentVolume
metadata:
  name: rords-volume
  namespace: rords
  labels:
    name: rords-volume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /mnt/local-volumes/rords
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nekomade # Edit this to be an actual kubernetes name of your server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rords-volume-claim
  namespace: rords
spec:
  selector:
    matchLabels:
      name: rords-volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi