apiVersion: v1
kind: Service
metadata:
  name: ror-dedicated-server
  namespace: rords
spec:
  ports:
    - name: game
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: serverlist
      port: 27016
      targetPort: 27016
      protocol: UDP
  selector:
    app: ror-dedicated-server
  externalIPs:
    - 158.69.157.240