apiVersion: v1
kind: Service
metadata:
  name: rords-service
  namespace: rords
spec:
  type: ClusterIP
  ports:
    - name: gametcp
      port: 27015
      targetPort: 27015
      protocol: TCP
    - name: gameudp
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: serverlisttcp
      port: 27016
      targetPort: 27016
      protocol: TCP
    - name: serverlistudp
      port: 27016
      targetPort: 27016
      protocol: UDP
  selector:
    app: ror-dedicated-server
  externalIPs:
    - 167.114.208.198