apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rords-pvc
  namespace: rords
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs