apiVersion: v1
kind: Secret
metadata:
  name: service-key
  namespace: cert-manager
  annotations:
    kubed.appscode.com/sync: "cert-manager-tls=nekomade-com"
type: kubernetes.io/tls
data:
  tls.crt: |
    ${{ secrets.nekomade_crt }}
  tls.key: |
    ${{ secrets.nekomade_key }}