# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ dev, main ]

jobs:
  # Gets the changed yaml files from the Deployments directory
  format_changed_paths:
    # If error is found, then the deployment will not succeed, so the workflow will stop
    continue-on-error: false
    # For speed and testing, will move to github hosted after
    runs-on: self-hosted
    # Provide Output for other steps and jobs to consume
    outputs:
      deployments: ${{ steps.filter.outputs.deployments }}
      deployments_files: ${{ steps.filter.outputs.deployments_files }}
      output_directories: ${{ steps.parse_paths.outputs.changed_output }}
    # Checks out the repo
    # Looks for any changed yaml file in the Deployments directory
    # Compiles a list of unique deployment directories and saves them as a json output format
    steps:
      # Checkout Repo
      - uses: actions/checkout@v2
      # Set up and run filter looking for altered yaml files
      - uses: dorny/paths-filter@v2.9.3
        id: filter
        with:
          list-files: json
          filters: |
            deployments:
              - added|modified: '**/*.yaml'
          base: 'dev'
          initial-fetch-depth: '10'
          working-directory: 'Deployments'
      # Passes in the files paths to find unique paths and saved results to a job output
      - id: parse_paths
        run: |
          input='${{ steps.filter.outputs.deployments_files }}' && \
          unique_directories=$(echo $(go run detectChanges.go $input) | sed 's/ //g' ) && \
          echo "::set-output name=changed_output::$unique_directories"


  # Uses the job to get the unique directories for each change found to deploy each edited unique directory
  Matrix_Deployment:
    # If there is an error, others could still succeed
    continue-on-error: true
    # Requires the previous job to get output data
    needs: format_changed_paths
    # Ensure changes have been made before attempting deployment
    if: ${{ needs.format_changed_paths.outputs.deployments == 'true' }}
    # Runs on self hosted until testing is complete
    runs-on: self-hosted
    # Matrix based on found unique directories in order to update any and all deployments
    strategy:
      matrix:
        include: ${{fromJson(needs.format_changed_paths.outputs.output_directories)}}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ needs.format_changed_paths.outputs.deployments_files }}" && \
          echo "${{ needs.format_changed_paths.outputs.output_directories }}" && \
          echo "Deploy: ${{ matrix.include }}"